//AUTHENTICATION
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNOUT = "SIGNOUT";

//MOVIES
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";

export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_ERROR = "GET_GENRES_ERROR";

export const FAVOURITE_CARD_SUCCESS = "FAVOURITE_CARD_SUCCESS";
export const FAVOURITE_CARD_ERROR = "FAVOURITE_CARD_ERROR";

//stocks

export const GET_ALL_COUNTRIES_SUCCESS = "GET_ALL_COUNTRIES_SUCCESS";
export const GET_ALL_COUNTRIES_ERROR = "GET_ALL_COUNTRIES_ERROR";

export const GET_STOCKS_COUNTRY_DATA_SUCCESS =
  "GET_STOCKS_COUNTRY_DATA_SUCCESS";
export const GET_STOCKS_COUNTRY_DATA_ERROR = "GET_STOCKS_COUNTRY_DATA_ERROR";

export const GET_ALL_INDUSTRIES_DATA_SUCCESS =
  "GET_ALL_INDUSTRIES_DATA_SUCCESS";
export const GET_ALL_INDUSTRIES_DATA_ERROR = "GET_ALL_INDUSTRIES_DATA_ERROR";

export const GET_STOCKS_COUNTRY_INDUSTRY_DATA_SUCCESS =
  "GET_STOCKS_COUNTRY_INDUSTRY_DATA_SUCCESS";
export const GET_STOCKS_COUNTRY_INDUSTRY_DATA_ERROR =
  "GET_STOCKS_COUNTRY_INDUSTRY_DATA_ERROR";
